config/routes.rb
Rails.application.routes.draw do
  match 'sessions/create', to: 'sessions#create', via: :post, as: 'login'
  match 'sessions/destroy', to: 'sessions#destroy', via: [:delete, :get], as: 'logout'

  get 'users/new', to: 'users#new', as: 'register'
  post 'users/create', to: 'users#create', as:'user'

  get 'users/:id/edit', to: 'users#edit', as: 'edit_profile'
  put 'users/:id', to: 'users#update', as: 'update_profile'

  get 'users/:id', to: 'users#show', as: 'profile'

  get 'users/forgotten'
  post 'users/send_forgotten'

  get 'download/:id/:aid', to: 'recipes#download', as: 'download'
  resources :recipes
  get 'home/welcome', as: :welcome

  root to: 'home#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :recipe

  def self.save_file(upload, recipe)
    dir = Rails.root.join('public', 'data')
    unless File.exists? dir
      Dir.mkdir dir
    end
    fname = upload.original_filename
    # fname.gsub!(/^\w\.\_/,"_")
    a = Attachment.new
    a.filename = fname
    a.mime = upload.content_type
    a.recipe = recipe
    a.save
    path = File.join(dir, a.id.to_s)
    File.open(path, 'wb') do |f| f.write(upload.read) end
    a.path = path
    a.save
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one :attachment
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  has_many :owned_recipes, class_name: "Recipe", foreign_key: 'user_id'
  has_and_belongs_to_many :recipes

  before_save :encrypt_password
  validates :email, {
      presence: true,
      uniqueness: true
  }
  validates :name, presence: true
  validates :password, confirmation: true, if: :password_required?

  def self.encrypt(salt, pass)
    Digest::SHA1.hexdigest(salt + pass)
  end

  def encrypt_password
    return if password.blank?
    if self.new_record?
      self.salt = SecureRandom.base64(8)
    end
    self.encrypted_password = User.encrypt(self.salt, self.password)
  end

  def self.authenticate(email, pass)
    user = User.where(email: email).first
    user && user.authenticated?(pass) ? user : nil
  end

  def authenticated?(pass)
    self.encrypted_password == User.encrypt(self.salt, pass)
  end

  def password_required?
    self.new_record? || !self.password.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :find_session
  protect_from_forgery with: :exception

  protected
  def find_session
    @current_user = User.find session[:user] if session[:user]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
      @recipe = Recipe.order("RAND()").first
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :download]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = if params[:search]
                 paginate(Recipe.where('category LIKE ?', "%#{params[:search]}%"), params[:page])
               else
                 paginate(Recipe.all, params[:page])
               end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(name: recipe_params[:name], category: recipe_params[:category], ingredients: recipe_params[:ingredients], description: recipe_params[:description])
    @recipe.owner = @current_user

    respond_to do |format|
      if @recipe.save
        unless params[:recipe][:attachment].nil?
          Attachment.save_file params[:recipe][:attachment], @recipe
        end
        format.html {redirect_to @recipe, notice: 'Recipe was successfully created.'}
        format.json {render :show, status: :created, location: @recipe}
      else
        format.html {render :new}
        format.json {render json: @recipe.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(name: recipe_params[:name], category: recipe_params[:category], ingredients: recipe_params[:ingredients], description: recipe_params[:description])
        unless params[:recipe][:attachment].nil?
          Attachment.save_file params[:recipe][:attachment], @recipe
        end
        format.html {redirect_to @recipe, notice: 'Recipe was successfully updated.'}
        format.json {render :show, status: :ok, location: @recipe}
      else
        format.html {render :edit}
        format.json {render json: @recipe.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html {redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def download
    a = Attachment.find params[:aid]
    send_file a.path, type: a.mime, disposition: :inline
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def paginate(recipes, page)
    recipes.paginate(page: page, per_page: 5)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:user_id, :name, :category, :ingredients, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate params[:email], params[:password]
    if @user
      flash[:notice] = "Logged in successfully"
      session[:user] = @user.id
      #redirect_to :back
      redirect_back(fallback_location: welcome_path)
    else
      flash[:notice] = "Invalid email address or password"
      #redirect_to :back
      redirect_back(fallback_location: welcome_path)
    end
  end

  def destroy
    reset_session
    flash[:notice] = "Logged out successfully"
    redirect_to welcome_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :show] # except: [:new, :create, :forgotten, :send_forgotten]
  def new
    @user = User.new
  end

  def create
    @user = User.new(name: user_params[:name], password: user_params[:password], email: user_params[:email], password_confirmation: user_params[:password_confirmation])
    if @user.save
      session[:user] = @user.id
      flash[:notice] = "Successful registration"
      redirect_to welcome_path
    else
      flash[:notice] = "Email address in use or password do not match"
      redirect_back(fallback_location: register_path)
    end
  end

  def edit
  end

  def update
    @user.update(name: user_params[:name], email: user_params[:email], password: user_params[:password], password_confirmation: user_params[:password_confirmation])
    redirect_to action: :show
  end

  def forgotten
  end

  def show
  end

  private
  def find_user
    @user = User.find params[:id]#session[:user]
  end

  def user_params
    params.require(:user).permit([:name, :password, :email, :password_confirmation])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    session[:user]
  end

  def recipe_owner?
    @recipe.owner == @current_user
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/welcome.html.erb
<h1>Welcome <%= @current_user.name if logged_in? %></h1>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eget nunc interdum, pulvinar justo non, iaculis
  elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras mauris metus,
  luctus congue mauris ac, convallis sollicitudin velit. Maecenas condimentum fermentum velit sed volutpat. Sed
  ultrices, nisl vel facilisis posuere, dolor ante dignissim tellus, eu dapibus erat nibh sed ipsum. Quisque scelerisque
  imperdiet pretium. Fusce vitae ullamcorper nunc, sit amet pretium sem. Nulla condimentum augue in enim luctus, vitae
  scelerisque augue rhoncus.
</p>
<p>
  Vestibulum et augue faucibus, tincidunt nunc in, ultrices lorem. Donec egestas ultricies mauris non blandit. Sed
  commodo, nunc sit amet convallis porta, ante felis tristique lacus, eu convallis turpis lectus id lectus. Aenean
  tempor convallis turpis. Sed neque libero, commodo vitae hendrerit nec, finibus eget dolor. Suspendisse potenti.
  Aenean diam libero, dictum ac massa sed, bibendum laoreet elit. Proin sed accumsan quam.
</p>
<h4>Today's offer:</h4>
<% unless @recipe.attachment.nil? %>
  <img height="200px" src="<%= download_path(@recipe.id, @recipe.attachment.id) %>">
<% end %>
<h6><%= link_to @recipe.name, @recipe %></h6>

app/views/layouts/_guest_menu.html.erb
<%= link_to "View recipes", recipes_path %><br/>

<fieldset>
  <legend>Login</legend>
  <%= form_tag login_path, method: :post do %>
    <%= label_tag 'email', "Email address" %>
    <%= text_field_tag 'email', '', size: 18 %><br/>
    <%= label_tag 'password', "Password" %>
    <%= password_field_tag 'password', '', size: 18 %><br/>
    <%= submit_tag 'Login' %>
  <% end %>
</fieldset>
<%= link_to "Register", '/users/new' %><br/>
<%= link_to "Forgotten password", '/users/forgotten' %>

app/views/layouts/_user_menu.html.erb
<p><%= link_to "View profile", profile_path(@current_user.id) %></p>
<p><%= link_to "Edit profile", edit_profile_path(@current_user.id) %></p>
<br>
<p><%= link_to "View recipes", recipes_path %></p>
<p><%= link_to "Add recipe", new_recipe_path %></p>
<br>
<p><%= link_to "Logout", logout_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipebook</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

<body>
<div id="body">
  <div id="header">
    <nav class="navbar navbar-expand-md navbar-fixed-top navbar-dark bg-dark main-nav">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li class="nav-item active">
            <%= link_to image_tag("home.ico", width: 20), '/' %>
          </li>
        </ul>
        <ul class="nav navbar-nav mx-auto">
          <li class="nav-item">
            <div class="nav-link">
              Website Name
            </div>
          </li>
        </ul>
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <div class="nav-link">
              <%= flash[:notice] %>
              <% if logged_in? %>
                <%= link_to "Logout", logout_path %>
              <% else %>
                <%= link_to "Register", register_path %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </div>
  <div id="main">
    <div id="menu">
      <% if logged_in? %>
        <%= render 'layouts/user_menu' %>
      <% else %>
        <%= render 'layouts/guest_menu' %>
      <% end %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :recipe_name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, [["Soup", "soup"], ["Main", "main"], ["Dessert", "dessert"]], id: :recipe_category %>
  </div>

  <div class="field">
    <%= form.label :attachment %>
    <%= form.file_field :attachment %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.text_field :ingredients, id: :recipe_ingredients %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 5, id: :recipe_description %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Delete', @recipe, method: :delete, data: {confirm: 'Are you sure?'} %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= params[:search] if params[:search] != "%" %> Recipes</h1>



<%= form_tag("/recipes", method: "get") do %>
  <%= label_tag(:search, "Search for:") %>
  <%= select_tag(:search, options_for_select([["All", "%"], ["Soup", "Soup"], ["Main", "Main"], ["Dessert", "Dessert"]])) %>
  <%= submit_tag("Search") %>
<% end %>

<%= will_paginate @recipes %>

<table>
  <thead>
  <tr>
    <th>Image</th>
    <th>Name</th>
  </tr>
  </thead>

  <tbody>
  <% @recipes.each do |recipe| %>
    <tr>
      <td>
        <% unless recipe.attachment.nil? %>
          <img width="80px" src="<%= download_path(recipe.id, recipe.attachment.id) %>">
        <% end %>
      </td>
      <td><%= link_to recipe.name, recipe %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @recipes %>

<% if logged_in? %>
  <%= link_to 'New Recipe', new_recipe_path, class: 'btn btn-primary' %>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @recipe.owner.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @recipe.category %>
</p>

<p>
  <strong>Image:</strong>
  <% unless @recipe.attachment.nil? %>
    <img width="250px" src="<%= download_path(@recipe.id, @recipe.attachment.id) %>"></img>
  <% end %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<% if recipe_owner? %>
  <%= link_to 'Edit', edit_recipe_path(@recipe), class: 'btn btn-warning' %> |
<% end %>
<%= link_to 'Back', recipes_path %>

app/views/users/edit.html.erb
<h1>Edit profile</h1>
<fieldset>
  <%= form_for :user, url: {controller: 'users', action: 'update'}, method: :put do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name, size: 20 %>
    </div>
    <div>
      <%= form.label :email %>
      <%= form.text_field :email, size: 40 %>
    </div>
    <div>
      <%= form.label :password %>
      <%= form.password_field :password, size: 20 %>
    </div>
    <div>
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, size: 20 %>
    </div>
    <%= form.submit "Save" %>
  <% end %>
</fieldset>
<%= link_to "Back", :back %>

app/views/users/forgotten.html.erb
<h1>Forgotten password</h1>
<fieldset>
  <legend>Please give your your email address</legend>
  <%= form_for :user, url: { controller: 'users', action: 'send_forgotten' }, method: :post do |form| %>
    <div>
      <%= form.label :email %>
      <%= form.text_field :email, size: 40 %>
    </div>
    <%= form.submit "Recover password" %>
  <% end %>
</fieldset>

app/views/users/new.html.erb
<h1>Register</h1>
<fieldset>
  <legend>Register a new user</legend>
  <%= form_for :user, url: { controller: 'users', action: 'create' }, method: :post do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name, size: 20 %>
    </div>
    <div>
      <%= form.label :email %>
      <%= form.text_field :email, size: 40 %>
    </div>
    <div>
      <%= form.label :password %>
      <%= form.password_field :password, size: 20 %>
    </div>
    <div>
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, size: 20 %>
    </div>
    <%= form.submit "Register" %>
  <% end %>
</fieldset>
<%= link_to "Back", :back %>

app/views/users/show.html.erb
<h1>User profile</h1>
<div>
  <b>Name:</b><%= @user.name %>
</div>
<div>
  <b>Email:</b><%= @user.email %>
</div>